Repository slaclab/pydm, pull requests merged in 2018-04, with the labels that each got.

#291 TST: Add tests for utilities.
  pydm/tests/utilities/__init__.py
  pydm/tests/utilities/test_colors.py
  pydm/tests/utilities/test_iconfont.py
  pydm/tests/utilities/test_macro.py
  pydm/tests/utilities/test_remove_protocol.py
  pydm/tests/utilities/test_units.py
  pydm/tests/utilities/test_utilities.py
  pydm/utilities/__init__.py
  pydm/utilities/iconfont.py
  pydm/utilities/macro.py
  pydm/utilities/remove_protocol.py
  pydm/utilities/units.py
Labels: docs, tests

#292 CI: Add support for AppVeyor (Windows)
  .coveragerc
  README.md
  appveyor.yml
  pydm/tests/utilities/test_utilities.py
Labels: ci

#290 ENH: Make MainWindow visible when calling PyDM without arguments.
  pydm/application.py
  pydm/main_window.py
  pydm_launcher/main.py
Labels: core, enhancement

#293 DOC: Adding utilities to the documentation tree.
  docs/source/conf.py
  docs/source/index.rst
  docs/source/utilities/index.rst
  pydm/utilities/colors.py
  pydm/utilities/iconfont.py
Labels: docs

#294 TST: Test for PyDM Push Button
  pydm/tests/conftest.py
  pydm/tests/widgets/test_pushbutton.py
  pydm/widgets/pushbutton.py
Labels: ci
