Repository slaclab/pydm, pull requests merged in 2018-07, with the labels that each got.

#364 Don't re-draw waveform plots unless the data has changed.
  pydm/widgets/waveformplot.py
Labels: enhancement

#349 ENH: Add support for PYDM_DISPLAYS_PATH variable.
  pydm/application.py
  pydm/main_window.py
  pydm/tests/utilities/test_utilities.py
  pydm/utilities/__init__.py
Labels: enhancement

#368 Fix crash in PyDMSymbol when the imageFiles attribute is invalid.
  pydm/widgets/symbol.py
Labels: bug

#377 ENH: Add version command to launcher.
  pydm_launcher/main.py
Labels: enhancement

#365 ENH: Add Widget Rules
  docs/source/_static/widgets/widget_rules/open_editor.gif
  docs/source/_static/widgets/widget_rules/rules_editor.png
  docs/source/configuration.rst
  docs/source/development/development.rst
  docs/source/index.rst
  docs/source/tutorials/macros.rst
  docs/source/widgets/widget_rules/customizing.rst
  docs/source/widgets/widget_rules/index.rst
  examples/actions/actions.ui
  examples/actions/actions2.ui
  pydm/application.py
  pydm/tests/conftest.py
  pydm/tests/test_plugins_import.py
  pydm/tests/widgets/test_base.py
  pydm/tests/widgets/test_rules.py
  pydm/tests/widgets/test_rules_editor.py
  pydm/widgets/base.py
  pydm/widgets/baseplot_qtplugin.py
  pydm/widgets/qtplugin_base.py
  pydm/widgets/qtplugin_extensions.py
  pydm/widgets/qtplugins.py
  pydm/widgets/rules.py
  pydm/widgets/rules_editor.py
  pydm/widgets/tab_bar_qtplugin.py
Labels: ci, core, enhancement, review started

#371 ENH: Add full screen mode capability to MainWindow.
  pydm/application.py
  pydm/main_window.py
  pydm/pydm.ui
  pydm/pydm_ui.py
  pydm_launcher/main.py
Labels: enhancement

#378 CI: Add OSX target
  .travis.yml
Labels: ci

#379 CI: Fix Conda Upload and remove BUILD_DOCS from osx.
  .travis.yml
Labels: ci
