Repository slaclab/pydm, pull requests merged in 2022-04, with the labels that each got.

#821 ENH: Change default text of PyDMLabel to ###### and display channel name when PV is not connected
  pydm/tests/widgets/test_label.py
  pydm/widgets/label.py
Labels: 1.15

#819 FIX: Don't keep the rolling window moving when zooming in on archiver plots
  pydm/tests/widgets/test_archiver_timeplot.py
  pydm/widgets/archiver_time_plot.py
Labels: 1.15

#820 ENH: Add a button for copying the list of all PVs to the clipboard from the connection inspector
  pydm/connection_inspector/connection_inspector.py
Labels: 1.15, 1.16

#817 FIX: ignores the rule editor expression in qt designer
  pydm/widgets/rules.py
Labels: 1.15, 1.16

#823 Deactivating the mouse wheel for the PyDMEnumComboBox
  pydm/widgets/enum_combo_box.py
Labels: 1.16

#833 FIX: Ensure PyDMChannel signals/slots are disconnected when a functools.partial is used
  pydm/data_plugins/plugin.py
Labels: 1.16

#830 FIX: Error when setting axis colors on a plot through designer
  pydm/widgets/baseplot.py
Labels: 1.16

#829 FIX: Ensure time plot x-axis receives all mouse events
  pydm/tests/widgets/test_baseplot.py
  pydm/widgets/archiver_time_plot.py
  pydm/widgets/baseplot.py
  pydm/widgets/timeplot.py
Labels: 1.16
