Repository slaclab/pydm, pull requests merged in 2022-05, with the labels that each got.

#835 ENH: Add an "Open in New Window" option to embedded displays
  pydm/widgets/embedded_display.py
Labels: 1.16

#849 BLD: new pyqt seems to break the test suite on the CI, pin for now
  conda-recipe/meta.yaml
Labels: codeathon

#795 ENH: add "basic settings" dialog for all PyDM widgets in the designer
  pydm/utilities/__init__.py
  pydm/widgets/designer_settings.py
  pydm/widgets/qtplugin_extensions.py
  pydm/widgets/qtplugins.py
Labels: 1.16

#844 REF/ENH: Entrypoints for external tools and data plugins
  conda-recipe/meta.yaml
  docs/source/data_plugins/external_plugins.rst
  docs/source/development/external_tools.rst
  docs/source/index.rst
  examples/external_tool/dummy_tool.py
  examples/external_tool/lookup_path/new_tool.py
  examples/external_tool/lookup_path/root_tool.py
  pydm/config.py
  pydm/data_plugins/__init__.py
  pydm/display.py
  pydm/tests/test_data_plugins_import.py
  pydm/tests/test_tools.py
  pydm/tests/utilities/test_utilities.py
  pydm/tools/__init__.py
  pydm/utilities/__init__.py
  requirements.txt
Labels: codeathon

#850 new PyDMDrawingIrregularPolygon widget
  docs/source/widgets/drawing.rst
  pydm/tests/test_plugins_import.py
  pydm/tests/widgets/test_drawing.py
  pydm/widgets/__init__.py
  pydm/widgets/drawing.py
  pydm/widgets/qtplugins.py
Labels: enhancement, in progress, codeathon

#843 Show macros command
  pydm/main_window.py
  pydm/show_macros/__init__.py
  pydm/show_macros/show_macros.py
  pydm/tests/test_show_macros.py
Labels: codeathon

#847 ENH: Add the ability to monitor changes to alarm limits of PVs
  pydm/data_plugins/epics_plugins/pyepics_plugin_component.py
  pydm/data_plugins/plugin.py
  pydm/tests/conftest.py
  pydm/tests/data_plugins/test_pyepics_plugin_component.py
  pydm/tests/widgets/test_base.py
  pydm/tests/widgets/test_channel.py
  pydm/widgets/base.py
  pydm/widgets/channel.py
Labels: codeathon

#856 Rename PyDMTimePlot's update modes #828
  pydm/tests/widgets/test_timeplot.py
  pydm/widgets/timeplot.py
Labels: codeathon

#875 ENH: Add monitoring of alarm limits to the caproto data plugin
  pydm/data_plugins/epics_plugins/caproto_plugin_component.py
Labels: 1.16

#879 FIX: Don't add an extra axis when creating plots through designer
  pydm/widgets/baseplot.py
Labels: 1.16

#878 FIX: Exception when using the show grid option in designer
  pydm/widgets/baseplot.py
  pydm/widgets/multi_axis_plot.py
Labels: 1.16

#786 ENH: Set log mode on or off on a per-axis basis in designer
  docs/source/widgets/curve_editor.rst
  pydm/tests/widgets/test_multiaxis_plot.py
  pydm/widgets/axis_table_model.py
  pydm/widgets/baseplot.py
  pydm/widgets/multi_axis_plot.py
Labels: 1.16

#883 FIX: do not create QIcons on import
  pydm/utilities/iconfont.py
  pydm/widgets/base.py
  pydm/widgets/qtplugin_base.py
  pydm/widgets/terminator.py
Labels: 1.16

#864 ENH added PyDMAnalogIndicator based on the PyDMScaleIndicator
  docs/source/_static/widgets/analog_indicator/analog_indicator.png
  docs/source/_static/widgets/analog_indicator/no_minor.png
  docs/source/_static/widgets/analog_indicator/no_upper_minor.png
  docs/source/_static/widgets/analog_indicator/smallest_size_set.png
  docs/source/_static/widgets/analog_indicator/smallest_size_visual.png
  docs/source/widgets/analog_indicator.rst
  pydm/widgets/analog_indicator.py
  pydm/widgets/qtplugins.py
Labels: 1.16

#839 ENH: Add pva plugin
  dev-requirements.txt
  docs/source/data_plugins/p4p_plugin.rst
  docs/source/index.rst
  examples/pva/image.ui
  examples/pva/labels.ui
  examples/pva/plots.ui
  examples/pva/writable_widgets.ui
  examples/testing_ioc/pva_testing_ioc.py
  pydm/data_plugins/epics_plugins/p4p_plugin_component.py
  pydm/data_plugins/epics_plugins/pva_codec.py
  pydm/data_plugins/pva_plugin.py
  pydm/tests/data_plugins/test_p4p_plugin_component.py
  run_tests.py
Labels: 1.16, codeathon
